language: java
jdk:
- oraclejdk8
node_js: "0.10"

before_install:
- cat /etc/hosts
- sudo hostname "$(hostname | cut -c1-63)"
- sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
- cat /etc/hosts
- npm install
- npm install grunt-cli -g

script:
- cd src/main/html/webapp;npm install;npm install;mkdir tmp;grunt
- mvn install
