site_name: Cloudgene v3
theme: material
pages:
- Home: index.md
- Installation: installation.md
- Getting started:
     - Install Apps: getting-started/installing-applications.md
     - Run Apps on the Commandline: getting-started/commandline.md
     - Run Apps in the Web Application: getting-started/web-application.md

- Cloudgene CLI:
    - Introduction: cli/introduction.md
    - cloudgene install: cli/cloudgene-install.md
    - cloudgene update: cli/cloudgene-update.md
    - cloudgene remove: cli/cloudgene-remove.md
    - cloudgene ls: cli/cloudgene-ls.md
    - cloudgene validate: cli/cloudgene-validate.md
    - cloudgene run: cli/cloudgene-run.md
    - cloudgene server: cli/cloudgene-server.md
    - cloudgene version: cli/cloudgene-version.md
- Cloudgene Daemon:
    - Introduction: daemon/introduction.md
    - Start Daemon: daemon/start-daemon.md
    - Stop Daemon: daemon/stop-daemon.md
    - Configuration: daemon/configuration.md
    - Manage Jobs: daemon/jobs.md
    - Manage Permissions: daemon/permissions.md
    - Maintenance: daemon/administration.md
- Developers:
    - Introduction: developers/introduction.md
    - Steps:
        - BashCommand: developers/steps/BashCommand.md
        - JavaJar: developers/steps/JavaJar.md
        - HadoopMapReduce: developers/steps/HadoopMapReduce.md
        - HadoopPig: developers/steps/HadoopPig.md
        - RMarkdown: developers/steps/RMarkdown.md
        - Docker: developers/steps/Docker.md
        - JavaInterface: developers/steps/JavaInterface.md
    - Inputs: developers/inputs.md
    - Outputs: developers/outputs.md
    - Control patterns: developers/control-patterns.md
- API Reference:
    - Introduction: api/introduction.md
    - Authentication: api/authentication.md
    - Submit Job: api/job-submission.md
    - Job Status: api/job-status.md
    - List Jobs: api/list-jobs.md
    - Job Details: api/job-details.md


extra:
  feature:
    tabs: true


markdown_extensions:
  - codehilite
  - admonition
  - toc(permalink=true)
  - footnotes
